### ISSUE TITLE
decidir el modelo de comunicación

### ISSUE THREAD

**Issue by ChacheGS** [CRM-UAM/Phogo#3]
A los diseñadores @molins @CarlosGS 
Veo dos alternativas:

1. Buffering: guardar las ordenes en un buffer
  * envio secuencial cuando se ha procesado el programa entero
  * si hay excepciones, no se procesa mas, y
  * no se abren conexiones innecesarias
  * si se manda, es que tiene sentido, y la conexion se abre y cierra limpiamente
2. Envio directo: sin buffer
  * no se procesa todo el programa antes de enviarlo
  * menor uso de memoria
  * se mantiene el socket BT abierto, aunque vaya a explotar
  * no se sabe cual es la ultima orden, y no se puede cerrar el socket en condiciones

**Comment by molins** [comment]
Tiene que ser **la segunda**. Fallo mío que no está en la wiki explicado. Me lo apunto!

Como hay una función para **leer el sensor de ultrasonidos** (y más peligroso aún, **estructuras de control de flujo**) no se puede hacer con buffer (o no al menos de una forma razonable).

**Comment by molins** [comment]
Si mi respuesta te satisface, cierra el issue, que queda más mono :+1:

**Comment by ChacheGS** [comment]
Claro que se puede hacer con buffer, a no ser que lo esté entendiendo mal. Buffer en el ordenador de hará las veces de hub de comunicaciones, en el propio proceso que usen los niños.
Pseudocódigo:
```
func enviar_programa() {
    socket.conectar()
	while (not buffer.empty()) {
		instruccion = buffer.pop()
        socket.enviar(instruccion)
        ack = socket.recibir()
		if (not ack == 'OK') {
			break;
		}
	}
    socket.desconectar()
}
```

**Comment by molins** [comment]
Imagina este pseudocódigo:

     if SensorUltrasonidos() > 10:
        Aanzar()
    else:
        Derecha()

¿Cómo quedaría la pila antes de mandarse al robot?

P.D.: Estoy en el móvil y no sé si este mensaje va a estar bien formateado…

**Comment by ChacheGS** [comment]
Vale, me había perdido ese comando, me quedé en que todos devolvían 'OK/ERR'. Descartado el buffer.
